/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TopRatedMoviesRouteImport } from './routes/top-rated-movies'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PopularTvShowsRouteImport } from './routes/popular-tv-shows'
import { Route as NowPlayingRouteImport } from './routes/now-playing'
import { Route as IndexRouteImport } from './routes/index'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRatedMoviesRoute = TopRatedMoviesRouteImport.update({
  id: '/top-rated-movies',
  path: '/top-rated-movies',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularTvShowsRoute = PopularTvShowsRouteImport.update({
  id: '/popular-tv-shows',
  path: '/popular-tv-shows',
  getParentRoute: () => rootRouteImport,
} as any)
const NowPlayingRoute = NowPlayingRouteImport.update({
  id: '/now-playing',
  path: '/now-playing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/now-playing': typeof NowPlayingRoute
  '/popular-tv-shows': typeof PopularTvShowsRoute
  '/search': typeof SearchRoute
  '/top-rated-movies': typeof TopRatedMoviesRoute
  '/trending': typeof TrendingRoute
  '/upcoming': typeof UpcomingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/now-playing': typeof NowPlayingRoute
  '/popular-tv-shows': typeof PopularTvShowsRoute
  '/search': typeof SearchRoute
  '/top-rated-movies': typeof TopRatedMoviesRoute
  '/trending': typeof TrendingRoute
  '/upcoming': typeof UpcomingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/now-playing': typeof NowPlayingRoute
  '/popular-tv-shows': typeof PopularTvShowsRoute
  '/search': typeof SearchRoute
  '/top-rated-movies': typeof TopRatedMoviesRoute
  '/trending': typeof TrendingRoute
  '/upcoming': typeof UpcomingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/now-playing'
    | '/popular-tv-shows'
    | '/search'
    | '/top-rated-movies'
    | '/trending'
    | '/upcoming'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/now-playing'
    | '/popular-tv-shows'
    | '/search'
    | '/top-rated-movies'
    | '/trending'
    | '/upcoming'
  id:
    | '__root__'
    | '/'
    | '/now-playing'
    | '/popular-tv-shows'
    | '/search'
    | '/top-rated-movies'
    | '/trending'
    | '/upcoming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NowPlayingRoute: typeof NowPlayingRoute
  PopularTvShowsRoute: typeof PopularTvShowsRoute
  SearchRoute: typeof SearchRoute
  TopRatedMoviesRoute: typeof TopRatedMoviesRoute
  TrendingRoute: typeof TrendingRoute
  UpcomingRoute: typeof UpcomingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-rated-movies': {
      id: '/top-rated-movies'
      path: '/top-rated-movies'
      fullPath: '/top-rated-movies'
      preLoaderRoute: typeof TopRatedMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular-tv-shows': {
      id: '/popular-tv-shows'
      path: '/popular-tv-shows'
      fullPath: '/popular-tv-shows'
      preLoaderRoute: typeof PopularTvShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now-playing': {
      id: '/now-playing'
      path: '/now-playing'
      fullPath: '/now-playing'
      preLoaderRoute: typeof NowPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NowPlayingRoute: NowPlayingRoute,
  PopularTvShowsRoute: PopularTvShowsRoute,
  SearchRoute: SearchRoute,
  TopRatedMoviesRoute: TopRatedMoviesRoute,
  TrendingRoute: TrendingRoute,
  UpcomingRoute: UpcomingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
